# config.py

# Model Paths
GAS_BOTTLE_DETECTION_YOLO_PATH = ""
TARRA_AND_YEAR_DETECTION_YOLO_PATH = ""
CLASSIFIER_MODEL_PATH = ""

# Video Paths
VIDEO_INPUT_PATH = ""
VIDEO_OUTPUT_PATH = ""

# Other Paths
GROUND_TRUTH_PATH = ""
TRACKER_CONFIG_PATH = "bytetrack_custom.yaml"
